In [1]:
import numpy as np

In [2]:
x = np.array([])

In [3]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [4]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [5]:
z = np.array([7,8,9])

In [6]:
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# İki boyut

In [7]:
a = np.array([[1,2,3],[4,5,6]])

In [8]:
np.concatenate([a,a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [13]:
np.concatenate([a,a], axis = 0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])