# Index ile Elemanlara Erişmek

In [1]:
import numpy as np
a = np.random.randint(10, size = 10)
a

array([8, 9, 1, 1, 4, 6, 1, 7, 6, 5])

In [2]:
a[0] 

8

In [3]:
a[0] = 100

In [4]:
a

array([100,   9,   1,   1,   4,   6,   1,   7,   6,   5])

In [6]:
m = np.random.randint(10, size = (3,5))
m

array([[1, 9, 9, 9, 5],
       [9, 3, 8, 5, 2],
       [6, 5, 9, 7, 8]])

In [8]:
m[0,0]

1

In [10]:
m[1,4]

2

In [11]:
m

array([[1, 9, 9, 9, 5],
       [9, 3, 8, 5, 2],
       [6, 5, 9, 7, 8]])

In [15]:
m[1,4] = 3.2

In [16]:
m[1,4]

3