# Matematiksel İşlemler

In [2]:
import numpy as np
v = np.array([1,2,3,4,5])

In [3]:
v-1

array([0, 1, 2, 3, 4])

In [4]:
v*5

array([ 5, 10, 15, 20, 25])

In [5]:
v/5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [6]:
v*5/10-1

array([-0.5,  0. ,  0.5,  1. ,  1.5])

### ufunc

In [8]:
np.subtract(v,1) #tüm elemanlardan verilen rakamı çıkar

array([0, 1, 2, 3, 4])

In [9]:
np.add(v,1) #tüm elemanlara verilen rakamı ekle

array([2, 3, 4, 5, 6])

In [10]:
np.multiply(v,4) #tüm elemanları verilen rakamla çarp

array([ 4,  8, 12, 16, 20])

In [12]:
np.divide(v,3) #tüm elemanları verilen rakama böl

array([0.33333333, 0.66666667, 1.        , 1.33333333, 1.66666667])

In [13]:
v**2

array([ 1,  4,  9, 16, 25], dtype=int32)

In [14]:
v**3

array([  1,   8,  27,  64, 125], dtype=int32)

In [16]:
np.power(v,3) #tüm elemanların verilen rakama göre üssünü al

array([  1,   8,  27,  64, 125], dtype=int32)

In [17]:
v % 2

array([1, 0, 1, 0, 1], dtype=int32)

In [18]:
np.mod(v,2) #verilen rakam bazında tüm elemanların modunu al

array([1, 0, 1, 0, 1], dtype=int32)

In [19]:
np.absolute(np.array([-3])) #mutlak değer alma

array([3])

In [20]:
np.sin(360)

0.9589157234143065

In [21]:
v = np.array([1,2,3])

In [22]:
np.log(v)

array([0.        , 0.69314718, 1.09861229])

In [23]:
np.log2(v)

array([0.       , 1.       , 1.5849625])

In [26]:
#dökümantasyona ulaşmak

In [27]:
?np

Type:        module
String form: <module 'numpy' from 'C:\\Users\\Acer\\anaconda3\\lib\\site-packages\\numpy\\__init__.py'>
File:        c:\users\acer\anaconda3\lib\site-packages\numpy\__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://www.scipy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as `np`::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>>

In [28]:
#cheatsheet aradığın şeyi googlede girip sonuna bu kelimeyi ekle