# Array Sıralama(Sorting)

In [1]:
import numpy as np

In [2]:
v = np.array([2,1,4,3,5])

In [3]:
v

array([2, 1, 4, 3, 5])

In [4]:
np.sort(v)

array([1, 2, 3, 4, 5])

In [5]:
v

array([2, 1, 4, 3, 5])

In [6]:
v.sort()

In [7]:
v

array([1, 2, 3, 4, 5])

### iki boyutlu array sirlama

In [8]:
m = np.random.normal(20,5,(3,3))

In [9]:
m

array([[24.41004782, 24.33640364, 26.93830176],
       [24.20989892, 11.39465625, 11.73535644],
       [13.32292421, 20.67168407, 19.36175045]])

In [12]:
np.sort(m,axis=1) #satıra göre sıralama

array([[24.33640364, 24.41004782, 26.93830176],
       [11.39465625, 11.73535644, 24.20989892],
       [13.32292421, 19.36175045, 20.67168407]])

In [13]:
np.sort(m,axis=0) #sütuna göre sıralama

array([[13.32292421, 11.39465625, 11.73535644],
       [24.20989892, 20.67168407, 19.36175045],
       [24.41004782, 24.33640364, 26.93830176]])

In [14]:
5*np.array([1,2,3])

array([ 5, 10, 15])