# Slicing ile Elemanlara Erismek(Array Alt Kümesine Erişmek)

In [2]:
import numpy as np

In [4]:
a = np.arange(20,30)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [5]:
a[0:3]

array([20, 21, 22])

In [6]:
a[:3]

array([20, 21, 22])

In [7]:
a[1::2]

array([21, 23, 25, 27, 29])

In [8]:
a[0::3]

array([20, 23, 26, 29])

### iki boyutlu slice islemleri

In [10]:
m = np.random.randint(10, size = (5,5))

In [11]:
m

array([[2, 4, 3, 6, 6],
       [8, 2, 3, 5, 0],
       [9, 2, 4, 4, 9],
       [5, 9, 5, 8, 1],
       [4, 9, 7, 0, 3]])

In [17]:
m[:,0] #sıfırıncı sütunu çekme

array([2, 8, 9, 5, 4])

In [18]:
m[:,1]

array([4, 2, 2, 9, 9])

In [19]:
m[:,4]

array([6, 0, 9, 1, 3])

In [20]:
m[0,:] #sıfırıncı satırı çekme

array([2, 4, 3, 6, 6])

In [21]:
m[0]

array([2, 4, 3, 6, 6])

In [22]:
m[1,:]

array([8, 2, 3, 5, 0])

In [23]:
m[0:2, 0:3] #m[satır,sütun]

array([[2, 4, 3],
       [8, 2, 3]])

In [24]:
m[:,:2]

array([[2, 4],
       [8, 2],
       [9, 2],
       [5, 9],
       [4, 9]])

In [25]:
m[1:3, 0:2]

array([[8, 2],
       [9, 2]])